### ISSUE TITLE
A bug appears

### ISSUE THREAD

**Issue by xtt790894620** [alphacsc/alphacsc#18]
when i try to import it,a bug appears,i do not know how to fix it,could you please help me?
 
type object 'alphacsc.cython_code.sparse_conv.array' has no attribute '__reduce_cython__'

**Comment by TomDLT** [comment]
How did you install the package?
Did you first install numpy and cython, and only then install alphacsc?
```
pip install numpy cython
pip install alphacsc
```

What cython version do you have?

**Comment by tomMoral** [comment]
@xtt790894620 Did you manage to solve your issue?

**Comment by picagrad** [comment]
We've also gotten this error recently.

Versions are numpy  1.17.3 and cython 0.29.2

Which versions is the stable version running on?

**Comment by jasmainak** [comment]
I have no problem importing `alphacsc` with your version of numpy and cython. You need to tell us what steps to follow to reproduce the problem, otherwise it's hard to help

Do you have `mne` installed by any chance (or just pip install it)? Can you tell us what is the output of `mne.sys_info()`?

**Comment by picagrad** [comment]
I've just realised that the version numbers I reported are the ones after I
managed to fix it and get it to load.

So these versions work. Not sure which exact versions I was running before
the fix. In any case, it would be amazing if you could report the versions
that are verified to work in the readme! Especially if and when the repo is
updated.

Thanks again for this awesome code!

**Comment by tomMoral** [comment]
It seems like this issue can be closed.
Feel free to open a new one if this bug persists!
