### ISSUE TITLE
Fix bug in compute objective

### ISSUE THREAD

**Issue by hndgzkn** [alphacsc/alphacsc#53]
Fix https://github.com/alphacsc/alphacsc/blob/0223c569a474896dd1cd21709b559ecfefa170ad/alphacsc/loss_and_gradient.py#L70 and https://github.com/alphacsc/alphacsc/blob/0223c569a474896dd1cd21709b559ecfefa170ad/alphacsc/loss_and_gradient.py#L72 by replacing `safe_sum(z_hat)` with `safe_sum(abs(z_hat))`

**Comment by tomMoral** [comment]
closing this issue as in `alphacsc` the activations are supposed to be positive.
