### ISSUE TITLE
TypeError: super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by jdslatermd** [alphacsc/alphacsc#9]
Greetings. 

In trying to run any of the examples, the call to convolutional_dictionary_learning.py consistently gives the above error. From online posts it seems like it is Python3 syntax that isn't compatible with 2.7. Is that a bug or am I simply misunderstanding which python you work in?

Thanks!

JDS

**Comment by agramfort** [comment]
@jdslatermd can you paste the full trace back?

we only test on Python 3.6 on travis. I don't know how easy it would be to also support python 2 although it seems a bit an overkill on 2018.

**Comment by jdslatermd** [comment]
That was easy - we use both because of a lot of legacy code. Switched to 3, installed the dependencies and the code runs flawlessly. Thanks!
